<div class="startPage">
    <h1>
        <img src="/images/icons/001_57.png" alt="Communicator" title="Communicator">
        Communicator
    </h1>
    <p>Sistema utilizado para comunicação interna entre funcionarios da empresa. </p><br/>

    <a id="links" class="blue" alt="Entrar Communicator" title="Entrar Communicator" href="/communicator">Entrar</a>

    <div class="clearfix"></div>
    <br/>
</div>


<div class="startPage">
    <h1>
        <img src="/images/icons/001_50.png" alt="Webdesk" title="Webdesk">
        WebDesk
    </h1>
    <p>Sistema webdesk utilizado para abrir chamados para os departamentos da empresa.</p>
    <a id="links" class="blue" alt="Entrar WebDesk" title="Entrar WebDesk" href="/webdesk">Entrar</a>
     <div class="clearfix"></div>
      <br/>
</div>


