<!--
 *@author Fabio Pratta <fabiobrotas@hotmail.com> 
 *@copyright Copyright - SIGP
 *@version 1.0 16/10/2012
-->
<div class="clearfix"></div>
<div id="view-content">

    <a href="/webdesk/departamentos" id="links" class="black">
        <img src="<?= $this->baseUrl('/images/icons/001_09.png') ?>" title="Novo Departamento" alt="Novo Departamento"/>
        Novo Departamento
    </a>


    <div class="clearfix"></div>
    <div id="list" class="tickets">
        <table id="list-ticktes"  width="100%">
            <colgroup>
                <col width="10%">
                <col width="60%">
                <col width="10%">
                
            </colgroup>

            <thead>
                <tr>
                    <th>ID</th>
                    <th>Departamento</th>
                    <th>Ação</th>
                </tr>
            </thead>

            <tbody>
                <?php if (sizeof($this->paginator)): ?>

                <script type="text/javascript">
                    $(document).ready(function() {
                        $('#list-ticktes').dataTable({
                            "bLengthChange": false
                        });
                    } );
                </script>
                <?php
                foreach ($this->paginator as $departamento):
                    ?>
                    <tr>  
                        <td><?= $departamento->id ?></td>
                        <td><?= $departamento->departamento ?></td>
                        <td align="center">
                            <a href="<?= $this->getUrl(array("module" => "webdesk", "controller" => "departamentos", "action" => "delete", "id" => $departamento->id)) ?>" title="Deletar">
                                <img src="<?= $this->baseUrl("/images/icons/001_05.png") ?>" title="Deletar" alt="Deletar" />
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan=2">Nenhum departamento encontrado!</td>
                </tr>
            <?php endif; ?>
            </tbody>


        </table>

    </div>

</div>
<div class="clearfix"></div>