<?= $this->partial("header.phtml") ?>
<?

//get layout of module
$module = $this->getModuleName();

switch ($module) {
    
    //LOGIN
    case "authenticate":
        ?>
        <!-- BEGIN MENU LEFT SECTION -->
        <section id="content">
            <?= $this->layout()->content ?>      
        </section>
        <!-- END MENU LEFT SECTION -->  
        <?
        break;
    
    
    //LOGIN
    case "default":
        ?>
        <!-- BEGIN MENU LEFT SECTION -->
        <section id="content">
            <?= $this->layout()->content ?>      
        </section>
        <!-- END MENU LEFT SECTION -->  
        <?
        break;

    //WEBDESK
    case "webdesk":
        ?>
        <section id="menu_top">
            <?= $this->partial("menu_top-webdesk.phtml") ?>    
        </section>
        <section id="content-wrap">

            <!-- BEGIN MENU LEFT SECTION -->
            <section id="menu_left">
                <?= $this->partial("menu-webdesk.phtml") ?>        
            </section>
            <!-- END MENU LEFT SECTION -->  



            <!-- BEGIN MENU LEFT SECTION -->
            <section id="content-webdesk">
                <?= $this->layout()->content ?>      
            </section>
            <!-- END MENU LEFT SECTION -->  

        </section>  
        <?
        break;

    default:
        break;
}
?>

<?= $this->partial("footer.phtml") ?>    

