<!--
 *@author Fabio Pratta <fabiobrotas@hotmail.com> 
 *@copyright Copyright - SIGP
 *@version 1.0 16/10/2012
-->
<div class="clearfix"></div>
<div id="view-content">

    <a href="/webdesk/parceiros" id="links" class="black">
        <img src="<?= $this->baseUrl('/images/icons/001_09.png') ?>" title="Novo Parceiro" alt="Novo Parceiro"/>
        Novo Parceiro
    </a>


    <div class="clearfix"></div>
    <div id="list" class="tickets">
        <table id="list-ticktes"  width="100%">
            <colgroup>
                <col width="30%">
                <col width="30%">
                <col width="15%">
                <col width="15%">
                <col width="10%">
            </colgroup>

            <thead>
                <tr>
                    <th>Empresa</th>
                    <th>Nome</th>
                    <th>Email</th>
                    <th>Telefone</th>
                    <th>Ação</th>
                </tr>
            </thead>

            <tbody>
                <?php if (sizeof($this->paginator)): ?>

                <script type="text/javascript">
                    $(document).ready(function() {
                        $('#list-ticktes').dataTable({
                            "bLengthChange": false
                        });
                    } );
                </script>
                <?php
                foreach ($this->paginator as $parceiros):
                    ?>
                    <tr>  
                        <td><?= $parceiros->departamento ?></td>
                        <td><?= $parceiros->nome ?></td>
                        <td><?= $parceiros->email ?></td>
                        <td><?= $parceiros->telefone ?></td>
                        <td align="center">
                            <a href="<?= $this->getUrl(array("module" => "webdesk", "controller" => "parceiros", "action" => "edit", "id" => $parceiros->idp)) ?>" title="Alterar">
                                <img src="<?= $this->baseUrl("/images/icons/001_45.png") ?>" title="Alterar" alt="Alterar" />
                            </a>
                            <a href="<?= $this->getUrl(array("module" => "webdesk", "controller" => "parceiros", "action" => "delete", "id" => $parceiros->idp)) ?>" title="Deletar">
                                <img src="<?= $this->baseUrl("/images/icons/001_05.png") ?>" title="Deletar" alt="Deletar" />
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan=2">Nenhum departamento encontrado!</td>
                </tr>
            <?php endif; ?>
            </tbody>


        </table>

    </div>

</div>
<div class="clearfix"></div>